/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtSpinner {
    }
    interface AtWeather {
        "city": string;
    }
}
declare global {
    interface HTMLAtSpinnerElement extends Components.AtSpinner, HTMLStencilElement {
    }
    var HTMLAtSpinnerElement: {
        prototype: HTMLAtSpinnerElement;
        new (): HTMLAtSpinnerElement;
    };
    interface HTMLAtWeatherElement extends Components.AtWeather, HTMLStencilElement {
    }
    var HTMLAtWeatherElement: {
        prototype: HTMLAtWeatherElement;
        new (): HTMLAtWeatherElement;
    };
    interface HTMLElementTagNameMap {
        "at-spinner": HTMLAtSpinnerElement;
        "at-weather": HTMLAtWeatherElement;
    }
}
declare namespace LocalJSX {
    interface AtSpinner {
    }
    interface AtWeather {
        "city"?: string;
    }
    interface IntrinsicElements {
        "at-spinner": AtSpinner;
        "at-weather": AtWeather;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "at-spinner": LocalJSX.AtSpinner & JSXBase.HTMLAttributes<HTMLAtSpinnerElement>;
            "at-weather": LocalJSX.AtWeather & JSXBase.HTMLAttributes<HTMLAtWeatherElement>;
        }
    }
}
